name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  go:
    name: Go tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: true
      - name: Check module tidiness
        run: |
          go mod tidy
          git diff --exit-code -- go.mod go.sum
      - name: Go format check
        run: |
          fmt_out=$(gofmt -l ./)
          if [ -n "$fmt_out" ]; then
            echo "$fmt_out" && echo "Go files need formatting" && exit 1
          fi
      - name: Tests
        run: go test ./...

  web:
    name: Web lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
